export const GOLD  = "#C9A84C";
export const BLACK = "#0A0A0A";
export const WHITE = "#FFFFFF";
export const SERIF = "'Cormorant Garamond', serif";
export const SANS  = "'Montserrat', sans-serif";

export const CATEGORIES = [
  "All","Weight Management","Recovery","Anti-Aging",
  "Performance","Aesthetics","Cognitive","Peptide Blends","Accessories",
];

export const PRODUCTS = [
  { id:"retatrutide",   name:"Retatrutide",             cat:"Weight Management",
    desc:"Triple receptor GLP-1/GIP/glucagon agonist commonly researched for advanced metabolic support and body composition.",
    variants:[{label:"5mg",price:220},{label:"10mg",price:380}] },
  { id:"tirzepatide",   name:"Tirzepatide",             cat:"Weight Management",
    desc:"Dual GIP/GLP-1 receptor agonist commonly researched for metabolic health and body composition improvement.",
    variants:[{label:"5mg",price:180},{label:"10mg",price:320}] },
  { id:"5amino",        name:"5-Amino-1MQ",             cat:"Weight Management",
    desc:"NNMT inhibitor commonly researched for fat cell metabolism activation and body recomposition support.",
    variants:[{label:"50mg",price:95}] },
  { id:"bpc157",        name:"BPC-157",                 cat:"Recovery",
    desc:"Body protection compound commonly researched for tissue repair, gut lining integrity, and accelerated healing.",
    variants:[{label:"5mg",price:65}] },
  { id:"cagrilintide",  name:"Cagrilintide",            cat:"Weight Management",
    desc:"Long-acting amylin analogue commonly researched for appetite regulation and sustained weight management.",
    variants:[{label:"5mg",price:200},{label:"10mg",price:340}] },
  { id:"cjcipamorelin", name:"CJC No DAC / Ipamorelin", cat:"Performance",
    desc:"Synergistic GHRH and GHRP combination commonly researched for growth hormone optimization and recovery.",
    variants:[{label:"5mg / 5mg",price:120}] },
  { id:"epithalon",     name:"Epithalon",               cat:"Anti-Aging",
    desc:"Tetrapeptide commonly researched for telomere elongation, circadian rhythm support, and longevity.",
    variants:[{label:"10mg",price:85}] },
  { id:"hghfrag",       name:"HGH Fragment 176-191",    cat:"Weight Management",
    desc:"Modified growth hormone fragment commonly researched for targeted lipolysis and fat metabolism.",
    variants:[{label:"5mg",price:75}] },
  { id:"ghkcu",         name:"GHK-Cu",                  cat:"Aesthetics",
    desc:"Copper peptide commonly researched for collagen synthesis, skin regeneration, and wound healing.",
    variants:[{label:"50mg",price:75}] },
  { id:"ipamorelin",    name:"Ipamorelin",              cat:"Performance",
    desc:"Selective growth hormone releasing peptide commonly researched for GH release with a clean safety profile.",
    variants:[{label:"5mg",price:85}] },
  { id:"kisspeptin",    name:"Kisspeptin",              cat:"Performance",
    desc:"Neuropeptide commonly researched for LH/FSH regulation, hormonal balance, and reproductive health.",
    variants:[{label:"10mg",price:120}] },
  { id:"klowblend",     name:"KLOW Blend",              cat:"Peptide Blends",
    desc:"Proprietary metabolic blend commonly researched for comprehensive weight management and metabolic optimization.",
    variants:[{label:"5mg",price:195}] },
  { id:"glowblend",     name:"GLOW Blend",              cat:"Peptide Blends",
    desc:"Proprietary aesthetic blend commonly researched for skin health, hair quality, and overall appearance support.",
    variants:[{label:"5mg",price:195}] },
  { id:"kpv",           name:"KPV Tripeptide",          cat:"Recovery",
    desc:"Alpha-MSH derived tripeptide commonly researched for anti-inflammatory action and gut barrier support.",
    variants:[{label:"50mg",price:75}] },
  { id:"lipoc",         name:"Lipo C with B12",         cat:"Weight Management",
    desc:"Lipotropic compound with Vitamin B12 commonly researched for fat mobilization and energy metabolism.",
    variants:[{label:"30mL",price:95}] },
  { id:"motsc",         name:"MOTS-C",                  cat:"Anti-Aging",
    desc:"Mitochondrial peptide commonly researched for metabolic flexibility, insulin sensitivity, and healthy aging.",
    variants:[{label:"10mg",price:145}] },
  { id:"melanotanI",    name:"Melanotan I",             cat:"Aesthetics",
    desc:"Alpha-MSH analogue commonly researched for skin pigmentation, UV photoprotection, and tanning.",
    variants:[{label:"10mg",price:95}] },
  { id:"melanotanII",   name:"Melanotan II",            cat:"Aesthetics",
    desc:"MSH analogue commonly researched for pigmentation, libido enhancement, and appetite suppression.",
    variants:[{label:"10mg",price:75}] },
  { id:"nad",           name:"NAD+",                    cat:"Anti-Aging",
    desc:"Essential coenzyme commonly researched for cellular energy production, DNA repair, and cognitive support.",
    variants:[{label:"500mg",price:120}] },
  { id:"pt141",         name:"PT-141",                  cat:"Aesthetics",
    desc:"Melanocortin receptor agonist commonly researched for sexual health, libido, and arousal support.",
    variants:[{label:"10mg",price:95}] },
  { id:"selank",        name:"Selank",                  cat:"Cognitive",
    desc:"Anxiolytic peptide commonly researched for stress reduction, anxiety relief, and memory enhancement.",
    variants:[{label:"5mg",price:85}] },
  { id:"semax",         name:"Semax",                   cat:"Cognitive",
    desc:"ACTH-derived nootropic peptide commonly researched for focus, neuroprotection, and mood stabilization.",
    variants:[{label:"5mg",price:85}] },
  { id:"tesamorelin",   name:"Tesamorelin",             cat:"Anti-Aging",
    desc:"GHRH analogue commonly researched for visceral fat reduction, IGF-1 stimulation, and metabolic health.",
    variants:[{label:"2mg",price:145}] },
  { id:"tb500",         name:"TB-500",                  cat:"Recovery",
    desc:"Thymosin Beta-4 fragment commonly researched for injury recovery, flexibility, and tissue repair.",
    variants:[{label:"5mg",price:95}] },
  { id:"bacwater",      name:"BAC Water",               cat:"Accessories",
    desc:"Bacteriostatic water for safe reconstitution of lyophilized peptide research compounds.",
    variants:[{label:"30mL",price:20}] },
];

// GHK-Cu removed from Glow stack per update — still available individually in catalog
export const STACKS = [
  { id:"weightloss", icon:"⚖️", name:"Weight Loss Stack",         tagline:"Advanced Metabolic Protocol",
    desc:"Comprehensive multi-compound approach to metabolic support, appetite regulation, and body recomposition.",
    peptides:["Tirzepatide","Retatrutide","5-Amino-1MQ","Cagrilintide","HGH Fragment 176-191","Lipo C with B12"] },
  { id:"recovery",   icon:"🔄", name:"Recovery Stack",            tagline:"Accelerated Tissue Repair",
    desc:"Targeted compounds for musculoskeletal healing, gut health, and structural tissue recovery.",
    peptides:["BPC-157","TB-500","Ipamorelin","CJC No DAC / Ipamorelin","KPV Tripeptide"] },
  { id:"antiaging",  icon:"⏳", name:"Anti-Aging Stack",          tagline:"Longevity & Cellular Health",
    desc:"Research-backed compounds targeting telomere support, mitochondrial function, and cellular longevity.",
    peptides:["Epithalon","GHK-Cu","MOTS-C","NAD+","Tesamorelin"] },
  { id:"performance",icon:"⚡", name:"Performance Stack",         tagline:"Peak Physical Output",
    desc:"Optimized for athletes seeking elevated GH output, endurance, focus, and faster recovery.",
    peptides:["CJC No DAC / Ipamorelin","Ipamorelin","BPC-157","TB-500","Selank","Semax"] },
  { id:"glow",       icon:"✨", name:"Glow & Aesthetics Stack",   tagline:"Skin, Pigmentation & Beauty",
    desc:"Aesthetic compounds for skin quality, pigmentation, libido, and overall appearance enhancement.",
    peptides:["Melanotan I","Melanotan II","PT-141","KPV Tripeptide","Lipo C with B12","GLOW Blend"] },
  { id:"cognitive",  icon:"🧠", name:"Cognitive & Mood Stack",    tagline:"Mental Clarity & Focus",
    desc:"Nootropic stack for enhanced cognition, mood stabilization, stress resilience, and neuroprotection.",
    peptides:["Semax","Selank","PT-141","NAD+"] },
  { id:"klow",       icon:"🔥", name:"KLOW Metabolic Stack",      tagline:"Metabolic Optimization",
    desc:"Proprietary metabolic protocol combining the KLOW Blend with complementary compounds.",
    peptides:["KLOW Blend","5-Amino-1MQ","Cagrilintide"] },
];

export const PROMO_CODES = {
  WELCOME10:10, TRUPEP15:15, VIP20:20, MIAMI30:30, ELITE40:40,
  GOLD45:45, LOYAL50:50, STAFF50:50, WHOLESALE35:35, PARTNER40:40,
};

export const TESTIMONIALS = [
  { name:"Marcus R.",  stars:5, text:"Down 34 lbs in 12 weeks on the weight loss stack. The results speak for themselves." },
  { name:"Sophia L.",  stars:5, text:"My skin has never looked better. The glow stack completely transformed my complexion." },
  { name:"James T.",   stars:5, text:"Recovery time cut in half after switching to BPC-157 and TB-500. Total game changer." },
  { name:"Daniela M.", stars:5, text:"The cognitive stack keeps me sharp during 14-hour trading sessions. Remarkable clarity." },
  { name:"Rafael C.",  stars:5, text:"TruPep's quality and customer service are unmatched. Loyal customer for life." },
];
